[logger]                    # настройка логгера
    name = ""               # имя логгера
    enable = true           # активация
    level = "error"         # уровень (fatal, info, error , warn, debug, trace)
    timestamp = "none"      # вывод времени full, short, unix и none

[api]
    enable = false              # активация API сервера
    logging = false             # логирование запросов (ключ logger.level = "debug" или ниже)
    hostname = "0.0.0.0"        # хост          
    port = 3001                 # порт
    backlog = 511               # очередь баклога
    prefix = "/api"             # префикс
    connection_timeout = 0      # таймаут сервера в миллисекундах
    keep_alive_timeout = 5000   # таймаут keep-alive сервера в миллисекундах
    body_limit = "1mb"          # максимальный размер тела запроса (b, kb, mb)
    trust_proxy = false         # доверие proxy заголовку

[healthcheck]                               # настройки проверки здоровья
    enable = false                          # активация
    label = "healthcheck.restarter=true"    # метка поиска
    check_interval = "10s"                  # интервал проверки
    
[docker]                            # настройки докера
    socket = "/var/run/docker.sock" # путь к сокету docker (игнорируются если указан ключ host)
    host = ""                       # хост подключения
    port = 2375                     # порт подключения
    protocol = "http"               # протокол http, https и ssh
    ca = ""                         # путь файла до файла CA
    cert = ""                       # путь до файла сертификата
    key = ""                        # путь до файла ключа
    version = "v1.38"               # версия api docker
    ping_interval = "10s"           # интервал проверки